---
title: "graphics with ggplot2"
author: "Christin Khan"
date: "October 22, 2018"
output: html_document
---

# Learning ggplot2

We're learning ggplot2 It's going to be amazing!

## Load packages


```{r}

# install and load tidyverse which is a package of packages
install.packages("tidyverse")
library(tidyverse)
```

## Load National Parks data

```{r}

#National Parks in California
ca <- read.csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/ca.csv") 

#Acadia National Park
acadia <- read.csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/acadia.csv")

#Southeast US National Parks
se <- read.csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/se.csv")

#2016 Visitation for all Pacific West National Parks
visit_16 <- read.csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/visit_16.csv")

#All Nationally designated sites in Massachusetts
mass <- read.csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/mass.csv")



```
# explore data

```{R}

head(se)

View(SE)


```

#play with data where geom_point is a scatter plot

```{R}


ggplot(data = se) +
  geom_point(aes (x = year, y =visitors, color=state)) +
  theme_minimal()+
  xlab("Year") +
  ylab("Visitors") +
  ggtitle("Which Southeastern State is the Wildest?") +
  theme(legend.title = element_blank(),axis.text.x = element_text(angle = 45, size =14))
  

```

```{r}

ggplot(data = se) +
  geom_point(aes(x = year, y = visitors)) +
  facet_wrap(~ state, scales = "free") +
  theme_void()

```


```{r}

ggplot(data = se) +
  geom_jitter(aes(x = park_name, y = visitors, color = park_name), alpha = 0.4, width = 0.1) +
  theme_void() + coord_flip()

```
```{r}

ggplot(data = se) +
  geom_violin(aes(x = park_name, y = visitors)) +
  theme_void()

```

```{r}

ggplot(se) +
  geom_line(aes(x = year, y = visitors, color=park_name)) +
  theme_bw()

```
# multiple geoms on one plot


```{r}

ggplot(data = acadia, aes(x = year, y = visitors, color=park_name)) +
  geom_point() +
  geom_line() +
  geom_smooth() +
  theme_minimalist()

```
# bar charts + how to name and save your ggplot

```{r}

myplot <- ggplot(data = visit_16, aes(x = state, y = visitors)) +
geom_bar(stat = "identity")

myplot

ggsave("myplot.png", myplot)


```