---
title: "wrangling"
author: "Christin Khan"
date: "October 22, 2018"
output:
  word_document: 
    fig_caption: yes
  pdf_document: default
  html_document: default
---

#install packages

```{r}
library(tidyverse)  # install.packages("tidyverse")
```

#read in data

```{r}
## read gapminder csv. Note the readr:: prefix identifies which package it's in
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')
```

#look at the data

```{r}
head(gapminder) 
```
```{r}
tail (gapminder)
```

```{r}
summary (gapminder)  #summary stats
names (gapminder)    #column names
dim(gapminder)       #dimensions
ncol(gapminder)      #number of columns
nrow(gapminder)      #number of rows
```

# Dplyr!

#filter by rows

```{r}
filter(gapminder, lifeExp < 29)
filter(gapminder, country == "Mexico")
filter(gapminder, country %in% c("Mexico","Peru"))
filter(gapminder, country == "Mexico", year == 2002)
Sweden <- filter(gapminder, country == "Sweden")
summary (Sweden)
mean(Sweden$lifeExp)
```
#filter by columns

```{r}
select(gapminder,year,lifeExp)
select(gapminder, -continent, -lifeExp)
```
#use select and filter together

```{r}
gap_cambodia <- filter(gapminder, country == "Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp)
```
The pipe operator will change your life
```{r}
#this:
gapminder %>% head(3)
#is equivalent to:
head(gapminder,3)

# let's improve this with pipes!
gap_cambodia <- gapminder %>%
  filter(country == "Cambodia") %>%
  select(-continent, -lifeExp)

head(gap_cambodia)

```

#mutate adds new variables
```{r}

gapminder %>% 
  mutate(planet = "Earth")

gapminder %>% 
  mutate(gdp = pop * gdpPercap)

head(gapminder)

gapminder %>%
  filter(country %in% c("Egypt","Vietnam")) %>% 
  mutate (gdp = pop * gdpPercap) %>% 
  mutate(max_gdp = max(gdp))
  

```

#Groups!

```{r echo=TRUE}
##with mutate()
gap_grouped <- gapminder %>% 
  group_by(country) %>%
  mutate(gdp = pop * gdpPercap,
         max_gdp = max(gdp)) %>% 
  ungroup()
View(gap_grouped)

##with summarize() or summarise()
gap_summarized <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp = pop * gdpPercap) %>% 
  summarize(max_gdp = max(gdp)) %>% 
  ungroup()
```

## 'arrange()' arranges columns

```{r}
gap_summarized <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp = pop * gdpPercap) %>% 
  summarize(max_gdp = max(gdp)) %>% 
  ungroup() %>% 
  arrange(desc(max_gdp))
```
## read in gapminder data in wide format
```{r}
#read in data
co2 <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/co2.csv')
#explore
co2 %>% head()
co2 %>% dim()

##create a new gapminder variable with only 2007 data
gap_2007 <- gapminder %>% 
  filter(year == 2007)

gap_2007 %>%  dim()   #142 observations

##left_join gap_2007 to co2
lf <- left_join(gap_2007, co2, by = "country")
```


```{r}
library(tidyverse)

## wide format
gap_wide <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder_wide.csv')

## yesterday's format
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')
```
#look at data
```{r}
head(gap_wide)
str(gap_wide)
```
#start to gather
```{r}
gap_long <- gap_wide %>% 
  gather(key   = obstype_year,
         value = obs_values)

```
# exercise

```{r}
gap_long %>% 
  group_by(continent, obs_type) %>%
    summarize(means = mean(obs_values))
cont <- gap_long %>% 
  filter(obs_type == "lifeExp", 
         year > 1980) %>% 
  group_by(continent, year) %>% 
  summarize(mean_le = mean(obs_values))
ggplot(data = cont, aes(x = year, y = mean_le, color = continent)) + 
  geom_line() +
  labs(title = "Mean life expectancy",
       x = "Year",
       y = "Age (years)") 
## Additional customization
ggplot(data = cont, aes(x = year, y = mean_le, color = continent)) + 
  geom_line() +
  labs(title = "Mean life expectancy",
       x = "Year",
       y = "Age (years)",
       color = "Continent") +
  theme_classic() +
  scale_fill_brewer(palette = "Blues")  
```
```

